# services:
#   traefik:
#     image: "traefik:v3.3"
#     container_name: "traefik"
#     command:
#       - "--api.insecure=true"
#       - "--providers.docker=true"
#     ports:
#       - "80:80"
#       - "8080:8080"
#     volumes:
#       - "/var/run/docker.sock:/var/run/docker.sock"

# whoami:
#   image: traefik/whoami
#   labels:
#     - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"

services:
  stream-service:
    build:
      context: .
      dockerfile: apps/services/stream/Dockerfile
    environment:
      - HOST=0.0.0.0
    ports:
      - '3001:4000'

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    environment:
      - HOST=0.0.0.0
      - STREAM_SERVICE_URL=stream-service:4000
      - REGISTRY_PREFIX=jamalyusuff
      - API_BASE_URL=api:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager
    depends_on:
      - stream-service
    ports:
      - '3000:3000'
